import { ScrollAnimation } from "../../../utils/animations/scrollAnimation"
export const AnimatedBox = ({ title, image, orientation }) => {

    return (
        <ScrollAnimation orientation={orientation}>
            <div className="animatedBox-container">
                <div className="animatedBox-info">
                    <div>
                        <h2>{title}</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer turpis libero, volutpat non fermentum in, viverra vel diam. Aenean facilisis risus quis tellus aliquam, ac iaculis felis mollis. Sed quis mauris placerat, luctus massa eget, sagittis odio. Curabitur aliquam, nisl nec placerat lacinia, urna ipsum mollis purus, eget blandit eros lectus id urna. Pellentesque massa nunc, imperdiet quis pellentesque et, aliquam et urna. Donec leo erat, scelerisque sed vehicula nec, commodo sed urna. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer turpis libero, volutpat non fermentum in, viverra vel diam. Aenean facilisis risus quis tellus aliquam, ac iaculis felis mollis. Sed quis mauris placerat, luctus massa eget, sagittis odio. Curabitur aliquam, nisl nec placerat lacinia, urna ipsum mollis purus, eget blandit eros lectus id urna. Pellentesque massa nunc, imperdiet quis pellentesque et, aliquam et urna. Donec leo erat, scelerisque sed vehicula nec, commodo sed urna. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer turpis libero, volutpat non fermentum in, viverra vel diam. Aenean facilisis risus quis tellus aliquam, ac iaculis felis mollis. Sed quis mauris placerat, luctus massa eget, sagittis odio. Curabitur aliquam, nisl nec placerat lacinia, urna ipsum mollis purus, eget blandit eros lectus id urna. Pellentesque massa nunc, imperdiet quis pellentesque et, aliquam et urna. Donec leo erat, scelerisque sed vehicula nec, commodo sed urna. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer turpis libero, volutpat non fermentum in, viverra vel diam. Aenean facilisis risus quis tellus aliquam, ac iaculis felis mollis. Sed quis mauris placerat, luctus massa eget, sagittis odio. Curabitur aliquam, nisl nec placerat lacinia, urna ipsum mollis purus, eget blandit eros lectus id urna. Pellentesque massa nunc, imperdiet quis pellentesque et, aliquam et urna. Donec leo erat, scelerisque sed vehicula nec, commodo sed urna. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer turpis libero, volutpat non fermentum in, viverra vel diam. Aenean facilisis risus quis tellus aliquam, ac iaculis felis mollis. Sed quis mauris placerat, luctus massa eget, sagittis odio. Curabitur aliquam, nisl nec placerat lacinia, urna ipsum mollis purus, eget blandit eros lectus id urna. Pellentesque massa nunc, imperdiet quis pellentesque et, aliquam et urna. Donec leo erat, scelerisque sed vehicula nec, commodo sed urna. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer turpis libero, volutpat non fermentum in, viverra vel diam. Aenean facilisis risus quis tellus aliquam, ac iaculis felis mollis. Sed quis mauris placerat, luctus massa eget, sagittis odio. Curabitur aliquam, nisl nec placerat lacinia, urna ipsum mollis purus, eget blandit eros lectus id urna. Pellentesque massa nunc, imperdiet quis pellentesque et, aliquam et urna. Donec leo erat, scelerisque sed vehicula nec, commodo sed urna. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer turpis libero, volutpat non fermentum in, viverra vel diam. Aenean facilisis risus quis tellus aliquam, ac iaculis felis mollis. Sed quis mauris placerat, luctus massa eget, sagittis odio. Curabitur aliquam, nisl nec placerat lacinia, urna ipsum mollis purus, eget blandit eros lectus id urna. Pellentesque massa nunc, imperdiet quis pellentesque et, aliquam et urna. Donec leo erat, scelerisque sed vehicula nec, commodo sed urna. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer turpis libero, volutpat non fermentum in, viverra vel diam. Aenean facilisis risus quis tellus aliquam, ac iaculis felis mollis. Sed quis mauris placerat, luctus massa eget, sagittis odio. Curabitur aliquam, nisl nec placerat lacinia, urna ipsum mollis purus, eget blandit eros lectus id urna. Pellentesque massa nunc, imperdiet quis pellentesque et, aliquam et urna. Donec leo erat, scelerisque sed vehicula nec, commodo sed urna. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer turpis libero, volutpat non fermentum in, viverra vel diam. Aenean facilisis risus quis tellus aliquam, ac iaculis felis mollis. Sed quis mauris placerat, luctus massa eget, sagittis odio. Curabitur aliquam, nisl nec placerat lacinia, urna ipsum mollis purus, eget blandit eros lectus id urna. Pellentesque massa nunc, imperdiet quis pellentesque et, aliquam et urna. Donec leo erat, scelerisque sed vehicula nec, commodo sed urna. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer turpis libero, volutpat non fermentum in, viverra vel diam. Aenean facilisis risus quis tellus aliquam, ac iaculis felis mollis. Sed quis mauris placerat, luctus massa eget, sagittis odio. Curabitur aliquam, nisl nec placerat lacinia, urna ipsum mollis purus, eget blandit eros lectus id urna. Pellentesque massa nunc, imperdiet quis pellentesque et, aliquam et urna. Donec leo erat, scelerisque sed vehicula nec, commodo sed urna. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
                    </div>
                    <img src={image} />
                </div>
            </div>
        </ScrollAnimation>
    )
}
